### ISSUE TITLE
Error — Resource is not saved after installing the Linkstrategy

### ISSUE THREAD

**Issue by OlegAnTo2000** [matdave/linkstrategy#5]
MODX 3.0.3, no other extras installed, a clean site to test.

After installing, the resource page does not save. Shows bar status cyclically.

There's an error in the browser console:

![Снимок экрана 2023-09-13 173228](https://github.com/matdave/linkstrategy/assets/143202406/bf368df7-5acd-45e1-9c96-53cc52403a92)

**Comment by deJaya** [comment]
I see this issue in MODX 3.0.4-pl as well.

**Comment by matdave** [comment]
Sorry it's been a hectic couple months. Do you have details on the 500 error. Like what is the server saying the error is?

**Comment by deJaya** [comment]
This is the 500 error I see - plugin #13 in this case being LinkStrategy:

```
[26-Nov-2023 16:36:32 UTC] PHP Fatal error:  Uncaught Error: Call to a member function getVersionData() on null in /home/xxyyzz/modx3/core/cache/includes/elements/modx/revolution/modplugin/13.include.cache.php:9
Stack trace:
#0 /home/xxyyzz/modx3/core/src/Revolution/modScript.php(88): include()
#1 /home/xxyyzz/modx3/core/src/Revolution/modX.php(1706): MODX\Revolution\modScript->process()
#2 /home/xxyyzz/modx3/core/src/Revolution/Processors/Model/UpdateProcessor.php(192): MODX\Revolution\modX->invokeEvent()
#3 /home/xxyyzz/modx3/core/src/Revolution/Processors/Model/UpdateProcessor.php(93): MODX\Revolution\Processors\Model\UpdateProcessor->fireAfterSaveEvent()
#4 /home/xxyyzz/modx3/core/src/Revolution/Processors/Processor.php(189): MODX\Revolution\Processors\Model\UpdateProcessor->process()
#5 /home/xxyyzz/modx3/core/src/Revolution/modX.php(1771): MODX\Revolution\Processors\Processor->run()
#6 /home/xxyyzz/modx3/core/src/Revolution/modConnectorResponse.php(151): MODX\Revolution\modX->runProcessor()
#7 /home/xxyyzz/modx3/core/src/Revolution/modConnectorRequest.php(89): MODX\Revolution\modConnectorResponse->outputContent()
#8 /home/xxyyzz/modx3/core/src/Revolution/modConnectorRequest.php(77): MODX\Revolution\modConnectorRequest->prepareResponse()
#9 /home/xxyyzz/modx3/connectors/index.php(79): MODX\Revolution\modConnectorRequest->handleRequest()
#10 {main}
  thrown in /home/xxyyzz/modx3/core/cache/includes/elements/modx/revolution/modplugin/13.include.cache.php on line 9
```
